updated php and nginx runtimes
awslabs/aws-lambda-web-adapter pull request #148
Opened 2023-01-30 03:31 UTC by elonniu

*Issue #, if available:*

*Description of changes:*

- Added PHP and Nginx Runtimes.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-01-31 13:14 UTC, bnusunny requested changes

2023-01-31 13:14 UTC, bnusunny commented on examples/nginx/template.yaml
> +    Properties:
Need to add `BinaryMediaTypes` property for REST API to handle binary data.

```yaml
      BinaryMediaTypes:
        - '*~1*'
```

2023-01-31 13:14 UTC, bnusunny commented on examples/nginx-zip/template.yaml
> +    Properties:
Same here. Need to add `BinaryMediaTypes` for binary data processing for REST API.

2023-01-31 13:14 UTC, bnusunny commented on examples/nginx-zip/template.yaml
> +    Properties:
All REST APIs need this property.

2023-01-31 13:14 UTC, bnusunny commented on examples/laravel/README.md
> +$ aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
This line is not required. Can be removed.

2023-02-01 02:37 UTC, elonniu commented on examples/nginx/template.yaml
> +    Properties:
It was solved in a separate submission. Thank you for reminding.

2023-02-01 02:37 UTC, elonniu commented on examples/laravel/README.md
> +$ aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws
It was solved in a separate submission. Thank you for reminding.

2023-02-11 02:21 UTC, closed without merging