Optional gzip compression of responses
awslabs/aws-lambda-web-adapter pull request #157
Opened 2023-02-16 04:45 UTC by huntharo

*Issue #, if available:* None

*Description of changes:*
- Compress responses when the `COMPRESSION` env var is `true`, when the response is not already compressed, and when the `content-type` starts with `text/` or is one of a few known types such as `application/javascript`
- The list of mime types to compress is not configurable to align with the way CloudFront handles automatic compression if enabled - the list of mime types that should / should not be compressed is something that is largely configurable one time and does not need to be adjusted or excruciatingly specified by each consumer (like nginx requires)
- Set the `Content-Length` response header to have the correct compressed length
- Set the `Content-Encoding` response header to `gzip` if compression is performed

### Motivations
- This project is awesome and I'm going to incorporate it into the documentation and examples for my [MicroApps](https://github.com/pwrdrvr/microapps-core) framework as the suggested method for quickly converting web apps to run as Lambda functions
- Node.js is exceedingly slow at performing gzip compression, particularly of large response bodies
- Lambda functions exposed via CloudFront connected to Function URLs with SigV4 signing do not have another place where compression of the response can be guaranteed, particularly on non-cacheable responses (which CloudFront either never or sometimes does not compress)
- Rust compressing the response should be substantially faster (I didn't even measure it as I've done extensive measurements of Node.js gzip performance for other projects... it's bad)
- This is a feature I need to allow Lambda to tie or beat the current deployment pattern for an existing site 

### To-Do / Seeking Input
- [ ] Should the `COMPRESSION` env var name be the first name-spaced env var such as `LAMBDA_ADAPTER_COMPRESSION`?
- [ ] Do we have deployed integration tests that will confirm this works in the wild?  I wasn't sure where to put those
- [ ] I assume the lambda http crate is handling marking the response as base64 encoded and handling the base64 encoding when it sees the gzip content-encoding - could someone confirm that?  I see that nginx is sending gzip responses through the adapter so I assume this is all working correctly already
- [ ] The use of `unsafe` in one of the tests (not deployed code) was gross, but there does not appear to be a body function that takes a byte array so I had to fake it as a non-validated string - Any suggestions for that test would be welcome

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-02-16 08:58 UTC, bnusunny commented
Thanks for the contribution! 

Here are my suggestions. 

1. Let's use `AWS_LWA_ATUO_COMPRESSION` as the environment variable name. 
2. We deploy a go-httpbin app in the pipeline, run e2e tests againt it in beta account, and tear it down when finished. You could add tests to the initial set of e2e tests [here](https://github.com/awslabs/aws-lambda-web-adapter/blob/main/tests/e2e/main.rs). 
3. Yes, lambda http crate will base64 encode any response with non-empty `content-encoding`. 
4. No need to convert the encoded bytes to a String. Hyper accepts Vec[u8] as body.

2023-02-16 09:26 UTC, bnusunny commented
There are a few formatting issues. Please run `cargo fmt`. It will fix those issues.

2023-02-16 13:16 UTC, huntharo commented
> There are a few formatting issues. Could you run `cargo fmt`? It will fix them. 

Yup will do shortly!  Thanks for the quick feedback, that's very refreshing!

2023-02-16 13:43 UTC, huntharo commented
> 4. No need to convert the encoded bytes to a String. Hyper accepts Vec[u8] as body.

I should clarify: It's `httpmock` that only accepts a string for the mocked `body` response.  This is only in a unit test but there did not appear to be any other way to get `httpmock` to return unmodified bytes.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/5617868/219380901-17836ccb-2998-48be-bcb8-eec8bd31a834.png">

2023-02-17 12:40 UTC, huntharo commented
@bnusunny any chance this can be released quickly?  I'm really wanting to use it in a project.

2023-02-17 12:53 UTC, bnusunny commented
Just need one minor update in the README. See my last comment above.

2023-02-17 12:56 UTC, huntharo commented
> Just need one minor update in the README. See my last comment above. 

I only see two comments?  One about cargo fmt and the one answering my 4 questions?

2023-02-17 13:01 UTC, bnusunny requested changes

2023-02-17 13:01 UTC, bnusunny commented on tests/integ_tests.rs
> +        let gzipped_body = String::from_utf8_unchecked(gzipped_body.unwrap());
This is unnecessary. Could you remove this line? Without it, the code should be safe.

2023-02-17 13:01 UTC, bnusunny commented on tests/integ_tests.rs
> +        let gzipped_body = encoder.finish();
Could add unwrap here. 

```rust
let gzipped_body = encoder.finish().unwrap();
```

2023-02-17 13:01 UTC, bnusunny commented on README.md
> +**LAMBDA_ADAPTER_COMPRESSION** Lambda Web Adapter supports gzip compression for response body. This feature is disabled by default. Enable it by setting environment variable `AWS_LWA_ENABLE_COMPRESSI
@huntharo  One minor thing here: the name of the env var should be `**AWS_LWA_ENABLE_COMPRESSION**`.

2023-02-17 13:01 UTC, bnusunny commented
> > Just need one minor update in the README. See my last comment above.
> 
> I only see two comments? One about cargo fmt and the one answering my 4 questions?

Sorry, I forget to summit the review comments.

2023-02-17 13:16 UTC, huntharo commented on README.md
> +**LAMBDA_ADAPTER_COMPRESSION** Lambda Web Adapter supports gzip compression for response body. This feature is disabled by default. Enable it by setting environment variable `AWS_LWA_ENABLE_COMPRESSI
Ha... I got it inconsistent... right at bottom, wrong at the top, right in the code :).  Good catch!

2023-02-17 13:16 UTC, huntharo commented on tests/integ_tests.rs
> +        let gzipped_body = String::from_utf8_unchecked(gzipped_body.unwrap());
Yup this was fixed

2023-02-17 13:20 UTC, huntharo commented on tests/integ_tests.rs
> +        let gzipped_body = encoder.finish();
done

2023-02-17 13:20 UTC, huntharo commented on README.md
> +**LAMBDA_ADAPTER_COMPRESSION** Lambda Web Adapter supports gzip compression for response body. This feature is disabled by default. Enable it by setting environment variable `AWS_LWA_ENABLE_COMPRESSI
done

2023-02-17 13:21 UTC, huntharo commented
> > > Just need one minor update in the README. See my last comment above.
> > 
> > 
> > I only see two comments? One about cargo fmt and the one answering my 4 questions?
> 
> Sorry, I forgot to summit the review comments.

No problem!  All issues addressed, thanks for the feedback!

2023-02-17 13:35 UTC, bnusunny approved these changes

2023-02-17 13:35 UTC, merged

2023-02-17 15:02 UTC, bnusunny commented
Release v0.6.2 is out. The layers and docker images are published.

2023-02-21 01:41 UTC, huntharo commented
I can confirm this is working.  I'm using it in a few projects already!