SpringBoot Response Streaming using function url
awslabs/aws-lambda-web-adapter pull request #237
Opened 2023-05-26 04:09 UTC by soyer-dev

Added a new example that uses SpringBoot and response streaming.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-05-26 06:12 UTC, bnusunny requested changes
Thanks for this great example! 

I have a few comments. Could you please check them?

2023-05-26 06:12 UTC, bnusunny commented on examples/springboot-response-streaming-zip/.DS_Store
Please remove all the `.DS_Store` files.

2023-05-26 06:12 UTC, bnusunny commented on examples/springboot-response-streaming-zip/README.md
> +          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
Please update this template to show the configuration required for response streaming.

2023-05-26 06:12 UTC, bnusunny commented on examples/springboot-response-streaming-zip/app/src/main/java/com/amazonaws/demo/stream/controller/StreamFilesController.java
> +    @RequestMapping(value = "/files/{file_name}", method = RequestMethod.GET)
This method could be removed. The streaming one is good enough.

2023-05-26 06:12 UTC, bnusunny commented on examples/springboot-response-streaming-zip/app/src/main/java/com/amazonaws/demo/stream/controller/StreamFilesController.java
> +        if (!file.exists()) {
`filename` is from user input. We could lock it down to a specific directory to avoid security loopholes.

2023-05-26 06:15 UTC, bnusunny requested changes

2023-05-26 06:15 UTC, bnusunny commented on examples/springboot-response-streaming-zip/app/src/main/java/com/amazonaws/demo/stream/controller/StreamFilesController.java
> +import org.springframework.core.io.ByteArrayResource;
This is not used. Should be removed.

2023-05-26 06:15 UTC, bnusunny commented on examples/springboot-response-streaming-zip/app/src/main/java/com/amazonaws/demo/stream/controller/StreamFilesController.java
> +import java.nio.file.Files;
This is not used. Should be removed.

2023-06-01 03:55 UTC, soyer-dev commented
Completed the suggested changes, thanks.

2023-06-01 09:04 UTC, bnusunny approved these changes
LGTM

2023-06-01 09:04 UTC, merged