Add AWS_LWA_PORT as a fallback for readiness_check_port.
awslabs/aws-lambda-web-adapter pull request #246
Opened 2023-06-24 23:50 UTC by sprvgt

*Issue #, if available:* #245

*Description of changes:* Add `AWS_LWA_PORT` as a fallback for `readiness_check_port`.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2023-06-26 16:20 UTC, mbfreder requested changes
Thank you for your contribution. Could you please add tests for this?

2023-06-27 05:53 UTC, sprvgt commented
Updated the test, PTAL. Thanks!

2023-06-28 18:04 UTC, mbfreder approved these changes

2023-06-28 23:13 UTC, bnusunny commented
This looks good. Could you fix the small linking issue?

2023-06-29 04:41 UTC, merged